version: "3.9"

services:
  dotsocr:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dotsocr-vllm:0.9.1-runtime
    container_name: dotsocr
    command: >
      --model /models/DotsOCR
      --trust-remote-code
      --download-dir /models
      --host 0.0.0.0
      --port 8000
    environment:
      HF_HOME: /root/.cache/huggingface
      HF_MODEL_PATH: /models/DotsOCR
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      # HF_TOKEN: ${HF_TOKEN}   # only if needed
    volumes:
      - models:/models
      - hf_cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  models:
  hf_cache:
