# docker/docker-compose.yml
version: "3.9"

services:
  dotsocr-vllm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: dotsocr-vllm:0.9.1
    container_name: dotsocr-vllm
    ports:
      - "8000:8000"
    environment:
      # Optional, only if the HF repo ever becomes gated:
      # HF_TOKEN: ${HF_TOKEN}
      MODEL_ID: rednote-hilab/dots.ocr
      DOWNLOAD_DIR: /models
      MODEL_DIR: /models/DotsOCR
      VLLM_LOGGING_LEVEL: INFO
      # For NVIDIA Container Toolkit:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - models:/models   # persist weights & cache across restarts
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/v1/models"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 60s

volumes:
  models:
  hf_cache:




